### PR TITLE
Add required boolean and enum values

### PR DESCRIPTION
**Pull request by philschatz**
This adds a `required` boolean and if values can be an enum, the possible values.

### CODE REVIEW

**Comment by gr2m** [comment]
oh wow thanks Phil! I’ve tons local changes this is all very much work in progress, but I’ll incorporate your changes once I have my initial-version PR updated

**Comment by gr2m** [comment]
This changes `type: 'boolean'` to `type: ['true', 'false']`, was that intended?

**Comment by gr2m** [comment]
fixed in 9589b21

**Comment by philschatz** [comment]
Sorry for the late reply, I'm traveling but yes, thanks for fixing the boolean types that have `Either true or false` in the description 😄

**Pull request closed without merging**
